name: gcdc-iis

on:
  push:
    branches: [ "uat" ]

jobs:
  build:
    runs-on: cis-runner
    steps:
    - uses: actions/checkout@v3
    - name: Clean and Delete Publish Folder
      run: |
        Remove-Item -Path ./publish -Force -Recurse -ErrorAction SilentlyContinue
        New-Item -ItemType Directory -Path ./publish
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release --output ./publish

  deploy:
    needs: build
    runs-on: cis-runner
    steps:
    - name: Deploy to IIS
      run: |
        # Replace 'siteName' with your actual site name
        $siteName = 'uat.gulfcoastdevelopment.sa'
        $publishFolder = './publish'  # Adjust the path based on your project structure

        Stop-WebAppPool -Name $siteName

        # Stop the IIS site
        Stop-WebSite -Name $siteName

        Start-Sleep -Seconds 10

        # Copy the published files to the IIS site folder
        Copy-Item -Path "$publishFolder\*" -Destination "C:\inetpub\wwwroot\" -Force -Recurse -Exclude wwwroot\media, appsettings.json

        Start-WebAppPool -Name $siteName

        # Start the IIS site
        Start-WebSite -Name $siteName
      shell: powershell
